services:
  hot:
    build:
      context: .
      dockerfile: Containerfile.dev
    working_dir: /app
    volumes:
      - .:/app
      - claude-code-config:/root/.claude
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=ecto://db.sqlite3
      - LISTEN_PUBLIC=true
      - CLAUDE_CONFIG_DIR=/root/.claude
    stdin_open: true
    tty: true

volumes:
  claude-code-config:
