defmodule Hot.Repo.Migrations.ConvertArchivedToListBased do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # Convert existing archived cards to finished status (list_id = 3)
    execute """
    UPDATE cards SET list_id = 3 WHERE archived = true
    """

    # Remove the archived column as it's no longer needed
    alter table(:cards) do
      remove :archived
    end
  end

  def down do
    # Add archived column back
    alter table(:cards) do
      add :archived, :boolean, null: false, default: false
    end

    # Convert finished and cancelled cards back to archived=true
    execute """
    UPDATE cards SET archived = true WHERE list_id IN (3, 4)
    """
  end
end
