defmodule Hot.Repo.Migrations.RemoveListTableAddListTitleToCards do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # Add the new column without NOT NULL first
    alter table(:cards) do
      add :list_title, :text
    end

    # Migrate data from list_id to list_title
    execute """
    UPDATE cards SET list_title = (
      CASE lists.title
        WHEN 'trailers' THEN 'trailers'
        WHEN 'watching' THEN 'watching'
        WHEN 'cancelled' THEN 'cancelled'
        WHEN 'finished' THEN 'finished'
        ELSE 'trailers'
      END
    )
    FROM lists
    WHERE cards.list_id = lists.id
    """

    # Set any remaining null list_title values to 'trailers' as default
    execute "UPDATE cards SET list_title = 'trailers' WHERE list_title IS NULL"

    # SQLite doesn't support ALTER COLUMN, so we need to recreate the table
    # Create a new table with the same structure but with list_title NOT NULL
    create table(:cards_new, primary_key: false) do
      add :show_id, references(:shows, column: :id, name: "cards_new_show_id_fkey", type: :uuid)
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :position, :bigint, null: false
      add :description, :text
      add :title, :text, null: false
      add :list_title, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    # Copy data from old table to new table
    execute "INSERT INTO cards_new (id, title, description, position, list_title, show_id, inserted_at, updated_at) SELECT id, title, description, position, list_title, show_id, inserted_at, updated_at FROM cards"

    # Drop old table and rename new table
    drop table(:cards)
    rename table(:cards_new), to: table(:cards)

    # Drop the lists table
    drop table(:lists)
  end

  def down do
    alter table(:cards) do
      remove :list_title
      # This is the `down` migration of the statement:
      #
      #     remove :list_id
      #

      # add :list_id, references(:lists, column: :id, name: "cards_list_id_fkey", type: :uuid), null: false
    end
  end
end
