defmodule Hot.Repo.Migrations.AddSeasonsEpisodes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:seasons, primary_key: false) do
      add :show_id, references(:shows, column: :id, name: "seasons_show_id_fkey", type: :uuid),
        null: false

      add :number, :bigint, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:episodes, primary_key: false) do
      add :season_id,
          references(:seasons, column: :id, name: "episodes_season_id_fkey", type: :uuid),
          null: false

      add :plays, :bigint, null: false
      add :last_watched_at, :utc_datetime
      add :number, :bigint, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    drop constraint(:episodes, "episodes_season_id_fkey")

    drop table(:episodes)

    drop constraint(:seasons, "seasons_show_id_fkey")

    drop table(:seasons)
  end
end