defmodule Hot.Repo.Migrations.AddArchiveFieldsToCards do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:cards) do
      add :archived, :boolean, null: false, default: false
      add :archived_at, :utc_datetime
    end
  end

  def down do
    alter table(:cards) do
      remove :archived_at
      remove :archived
    end
  end
end
