defmodule Hot.Repo.Migrations.Identities do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:shows, [:title], name: "shows_unique_title_index")

    create unique_index(:shows, [:trakt_id], name: "shows_unique_trakt_id_index")

    create unique_index(:seasons, [:number], name: "seasons_unique_number_index")

    create unique_index(:episodes, [:season_id, :number],
             name: "episodes_unique_season_number_index"
           )
  end

  def down do
    drop_if_exists unique_index(:episodes, [:season_id, :number],
                     name: "episodes_unique_season_number_index"
                   )

    drop_if_exists unique_index(:seasons, [:number], name: "seasons_unique_number_index")

    drop_if_exists unique_index(:shows, [:trakt_id], name: "shows_unique_trakt_id_index")

    drop_if_exists unique_index(:shows, [:title], name: "shows_unique_title_index")
  end
end