defmodule Hot.Repo.Migrations.AllowEmptyCardTitles do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # SQLite doesn't support ALTER COLUMN, so we need to recreate the table
    # First, create a new table with the same structure but nullable title
    create table(:cards_new, primary_key: false) do
      add :show_id, references(:shows, column: :id, name: "cards_new_show_id_fkey", type: :uuid)
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :position, :bigint, null: false
      add :description, :text
      # This is the change
      add :title, :text, null: true
      add :list_title, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    # Copy data from old table to new table
    execute "INSERT INTO cards_new (id, title, description, position, list_title, show_id, inserted_at, updated_at) SELECT id, title, description, position, list_title, show_id, inserted_at, updated_at FROM cards"

    # Drop old table and rename new table
    drop table(:cards)
    rename table(:cards_new), to: table(:cards)
  end

  def down do
    # Recreate with NOT NULL constraint
    create table(:cards_new, primary_key: false) do
      add :show_id, references(:shows, column: :id, name: "cards_new_show_id_fkey", type: :uuid)
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :position, :bigint, null: false
      add :description, :text
      # Back to NOT NULL
      add :title, :text, null: false
      add :list_title, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    execute "INSERT INTO cards_new (id, title, description, position, list_title, show_id, inserted_at, updated_at) SELECT id, title, description, position, list_title, show_id, inserted_at, updated_at FROM cards WHERE title IS NOT NULL"
    drop table(:cards)
    rename table(:cards_new), to: table(:cards)
  end
end
