defmodule Hot.Repo.Migrations.ImdbId do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:shows) do
      add :imdb_id, :text
    end
  end

  def down do
    alter table(:shows) do
      remove :imdb_id
    end
  end
end