defmodule Hot.Repo.Migrations.CreateBoardTables do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:lists, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :position, :bigint, null: false
      add :title, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:lists, [:title], name: "lists_unique_title_index")

    create table(:cards, primary_key: false) do
      add :show_id, references(:shows, column: :id, name: "cards_show_id_fkey", type: :uuid)

      add :list_id, references(:lists, column: :id, name: "cards_list_id_fkey", type: :uuid),
        null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :position, :bigint, null: false
      add :description, :text
      add :title, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    drop constraint(:cards, "cards_list_id_fkey")

    drop constraint(:cards, "cards_show_id_fkey")

    drop table(:cards)

    drop_if_exists unique_index(:lists, [:title], name: "lists_unique_title_index")

    drop table(:lists)
  end
end
