defmodule :"Elixir.Hot.Repo.Migrations.Fix-unique-season" do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:seasons, [:number], name: "seasons_unique_number_index")

    create unique_index(:seasons, [:show_id, :number], name: "seasons_unique_show_number_index")
  end

  def down do
    drop_if_exists unique_index(:seasons, [:show_id, :number],
                     name: "seasons_unique_show_number_index"
                   )

    create unique_index(:seasons, [:number], name: "seasons_unique_number_index")
  end
end
